#!/bin/sh

# TODO: patches to either add or remove features (suckless philosophy)
# TODO: add comments to code
# TODO: explain grading system in help
# TODO: remove dependency on bc if possible
# TODO: look to anki's features for inspiration
# TODO: tweak spaced repitition algorithm

create_temp_deck() {
	DATE=$(date +%Y-%m-%d)
	if [ -n "$AHEADDAYS" ]; then get_date "$AHEADDAYS"; fi

	if [ "$RESCHEDULEFLAG" = "0" ]; then echo "\033[5;31mRescheduling off, deck will not be written to\033[0m"; fi

	if [ "$STDINFLAG" -eq 1 ]; then AWK_PATTERN="(NR > 0)"; else AWK_PATTERN="(NR > 1)"; fi
	if [ "$TAG" != ".*" ]; then AWK_PATTERN="$AWK_PATTERN && (\$4 ~ /$TAG/)"; fi
	if [ "$TOTALRECALLFLAG" != "1" ] || [ -n "$AHEADDAYS" ]; then AWK_PATTERN="$AWK_PATTERN && (\$8 <= date)"; fi
	if [ "$STDINFLAG" -eq 1 ]; then
		DECK_LINES=$(cat | awk -F'\t' -v date="$DATE" "$AWK_PATTERN")
	else
		DECK_LINES=$(awk -F'\t' -v date="$DATE" "$AWK_PATTERN" "$DECK")
	fi
	NUM_CARDS=$(echo "$DECK_LINES" | awk -F'\t' 'END {print NR}')
	if [ "$TOTALRECALLFLAG" != "1" ] && [ -z "$AHEADDAYS" ]; then
		DUE=$(echo "$DECK_LINES" | awk -F'\t' -v date="$DATE" 'BEGIN {i=0} $8 == date {i++} END {print i}')
		PAST_DUE=$(echo "$DECK_LINES" | awk -F'\t' -v date="$DATE" 'BEGIN {i=0} $8 < date {i++} END {print i}')
		if [ -z "$DECK_LINES" ]; then
			printf '\033[5;32mNo cards due!\033[0m\n'
		else
			printf '\033[5;33mDue today: %s card' "$DUE"
			if [ "$DUE" -ne 1 ]; then printf 's'; fi
			if [ "$PAST_DUE" -gt 0 ]; then printf '\033[5;31m (%s past due)' "$PAST_DUE"; fi
			printf '\033[0m\n'
		fi
	else
		if [ "$TOTALRECALLFLAG" = "1" ]; then printf '\033[5;33mTotal recall mode: '; fi
		if [ -n "$AHEADDAYS" ]; then printf '\033[5;33mReviewing ahead by %s days: ' "$AHEADDAYS"; fi
		printf '%s cards loaded\n' "$NUM_CARDS"
	fi
	unset DUE PAST_DUE
}

validate_deck() {
	ALL_LINES=$(cat "$1")
	if [ "$1" = "-" ]; then AWK_PATTERN="(NR > 0)"; else AWK_PATTERN="(NR > 1)"; fi
	TOTAL_LINES=$(echo "$ALL_LINES" | awk -F'\t' "$AWK_PATTERN"' {i++} END {print i}')
	# mawk (default on debian and ubuntu systems) does not support regex repetition braces, which makes ($1 ~ /^[a-f0-9]$/) not work
	# this is why im using these extra two checks with grep
	# the md5 id regex could just use /^[a-f0-9]+$/, but then ids greater or less than 32 chars long would match
	VALID1=$(echo "$ALL_LINES" | awk -F'\t' '
		'"$AWK_PATTERN"' &&
		(NF == 8) &&
		($4 ~ /^[a-zA-Z0-9,-]*$/) &&
		($5 ~ /^[0-9]+$/) &&
		($6 >= 1.3) &&
		($7 ~ /^[0-9]+$/)   { i++ } END { print i }')
	VALID2=$(echo "$ALL_LINES" | awk -F'\t' "$AWK_PATTERN"' { print $8 }' | grep -c "^[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}$")
	VALID3=$(echo "$ALL_LINES" | awk -F'\t' "$AWK_PATTERN"' { print $1 }' | grep -c "^[a-f0-9]\{32\}$")
	if [ "$TOTAL_LINES" = "$VALID1" ] && [ "$TOTAL_LINES" = "$VALID2" ] && [ "$TOTAL_LINES" = "$VALID3" ]; then
		VALID="valid"
	elif [ "$1" != "-" ]; then
		VALID="\033[5;31mDeck file '$1' invalid\033[0m"
	elif [ "$1" = "-" ]; then
		VALID="\033[5;31mDeck from stdin invalid\033[0m"
	fi
	if [ "$STDINFLAG" -eq 1 ] && [ "$VALID" = "valid" ] && [ "$1" != "-" ]; then
		validate_deck "-"
	fi
	unset ALL_LINES TOTAL_LINES VALID1 VALID2 VALID3
}

SM2() {
	case $1 in
		0|1|2 )
			REPETITION=0
			INTERVAL=1;;
		3|4|5 )
			if [ $REPETITION = 0 ]; then
				INTERVAL=1
			elif [ $REPETITION = 1 ]; then
				INTERVAL=6
			elif [ $REPETITION -gt 1 ]; then
				INTERVAL=$(echo "if ( $INTERVAL*$EASINESS%1 ) ($INTERVAL*$EASINESS)/1 + 1 else ($INTERVAL*$EASINESS)/1" | bc)
			fi

			EASINESS=$(echo "$EASINESS + (0.1 - (5 - $GRADE) * (0.08 + (5 - $GRADE) * 0.02))" | bc)
			if [ "$(echo "$EASINESS < 1.3" | bc)" = 1 ]; then
				EASINESS=1.3
			fi
			REPETITION=$(echo "$REPETITION+1" | bc);;

	esac
}

get_date() {
	if [ "$(uname)" = "Linux" ]; then
		DATE=$(date -d "+$1 days" +%Y-%m-%d)
	else
		DATE=$(date -v +"$1""d" +%Y-%m-%d)
	fi
}

review() {
	SEPARATOR="---------------------------------------------------------"
	if [ -n "$DECK_LINES" ]; then
		CARD_NUMBER=1
		echo "Let's review!"; echo "$DECK_LINES" | while IFS="$(printf '\t')" read -r ID FRONT BACK TAGS REPETITION EASINESS INTERVAL DATE; do
			if [ "$ZENFLAG" = "1" ]; then clear; fi
			OLD_LINE="$ID	$FRONT	$BACK	$TAGS	$REPETITION	$EASINESS	$INTERVAL	$DATE"
			echo "$SEPARATOR"
			printf '\033[1;32mFront:\033[0m %s \033[5;34m(#%s/%s)\033[0m\n' "$FRONT" "$CARD_NUMBER" "$NUM_CARDS"
			printf '\033[3;30mPress enter to show back...\033[0m'
			read -r _ < /dev/tty
			echo "\033[1;32mBack:\033[0m" "$BACK"
			while ! (echo "$GRADE" | grep -q "^[0-5]$"); do
				printf '\033[1;32mGrade (0-5): \033[0m'
				read -r GRADE < /dev/tty
			done

			SM2 "$GRADE"
			unset GRADE
			if [ "$RESCHEDULEFLAG" != "0" ]; then
				get_date "$INTERVAL"
				echo "\033[1;34mRepetition:\033[0m" "$REPETITION" "\033[1;34mEasiness:\033[0m" "$EASINESS" "\033[1;34mInterval:\033[0m" "$INTERVAL" "\033[1;34mDate:\033[0m" "$DATE"
				NEW_LINE="$ID	$FRONT	$BACK	$TAGS	$REPETITION	$EASINESS	$INTERVAL	$DATE"
				ID_OCCURENCES=$(grep -c "$ID" "$DECK")
				if [ "$ID_OCCURENCES" -gt 0 ]; then
					sed -i.bu "s/$OLD_LINE/$NEW_LINE/g" "$DECK"
					rm "$DECK".bu
				else
					echo "\033[5;33mCard ID not found in deck $DECK, adding to deck\033[0m"
					echo "$NEW_LINE" >> "$DECK"
				fi
			fi
			if [ "$ZENFLAG" = "1" ]; then
				printf '\033[3;30mPress enter to show next card...\033[0m'
				read -r _ < /dev/tty
			fi
			CARD_NUMBER=$((CARD_NUMBER+1))
			if [ "$RESCHEDULEFLAG" != "0" ] && [ "$CARD_NUMBER" -gt "$NUM_CARDS" ]; then 
				echo "$SEPARATOR"
			fi
		done
		if [ "$RESCHEDULEFLAG" != "0" ] && [ -z "$AHEADDAYS" ] && [ "$TOTALRECALLFLAG" != "1" ]; then
			create_temp_deck
		fi
	else
		echo "\033[5;32mNothing to review!\033[0m"
	fi
	unset SEPARATOR
}

tag_select() {
	echo "\033[1;32mAvailable tags:\033[0m"
	awk -F'\t' '{print $4}' "$DECK" | tail -n +2 | tr , '\n' | sort | uniq -c | sort -rn
	printf '\n\033[1;32mTag selection regex (or '\''all'\''): \033[0m'
	read -r TAG < /dev/tty
	if [ "$TAG" = "all" ]; then TAG='.*'; fi
	create_temp_deck
}

stats() {
	echo "\033[1;32mAvailable tags:\033[0m"
	awk -F'\t' '{print $4}' "$DECK" | tail -n +2 | tr , '\n' | sort | uniq -c | sort -rn
	echo "\033[1;32mDue dates:\033[0m"
	awk -F'\t' 'NR > 1 {print $8}' "$DECK" | sort | uniq -c
}

deck_select() {
	echo "\033[1;32mAvailable decks:\033[0m"
	ls ./*.tsv
	printf '\n\033[1;32mDeck: \033[0m'
	OLD_DECK=$DECK
	read -r DECK < /dev/tty
	validate_deck "$DECK"
	if [ "$VALID" = "valid" ]; then
		TAG='.*'
		create_temp_deck
	else
		echo "$VALID\033[5;31m, switching back to previous deck"
		DECK=$OLD_DECK
	fi
	unset OLD_DECK
}

import() {
	if [ "$RESCHEDULEFLAG" -eq 0 ]; then printf "id\tfront\tback\ttags\trepetition\teasiness\tinterval\tdue\n"; fi
	if [ "$STDINFLAG" -eq 1 ]; then
		cat | awk -F'\t' -v date="$(date +%Y-%m-%d)" '{OFS=FS;
								system("printf \"$(head -n 1 /dev/random | md5)\t\"");
								print $0, 0, 2.5, 0, date;}'
	else
		awk -F'\t' -v date="$(date +%Y-%m-%d)" '{OFS=FS;
							system("printf \"$(head -n 1 /dev/random | md5)\t\"");
							print $0, 0, 2.5, 0, date;}' "$1"
	fi
}

main() {
	while true; do
		printf '\033[1;33m> \033[0m'
		read -r PROMPT_INPUT < /dev/tty

		case $PROMPT_INPUT in
			r|review )
				review
				;;
			t|tag )
				tag_select
				;;
			d|deck )
				deck_select
				;;
			s|stats )
				stats
				;;
			h|help )
				printf "type review/r to review
press tag/t for tag select
press deck/d for deck select
press stats/s for stats
press help/h for help
press quit/q to quit\n\n"
				;;
			q|quit )
				echo "Quitting..."; break;;
			* )
				echo "What??";;
		esac
	done
}

DECK='db.tsv'
TAG='.*'

IMPORTFLAG=
TOTALRECALLFLAG=
AHEADDAYS=
RESCHEDULEFLAG=1
ZENFLAG=
STDINFLAG=
if [ -t 0 ]; then STDINFLAG=0; else STDINFLAG=1; fi
while getopts i:d:f:a:htrz name
do
    case $name in
    d)
	if [ ! -f "$OPTARG" ]; then
		printf "\033[5;31mNo deck called %s found\033[0m\n" "$OPTARG"
		exit 1;
	else
		DECK="$OPTARG"
	fi
	;;
    i)    
	IMPORTFLAG=1
	IMPORT="$OPTARG";;
    t)
	TOTALRECALLFLAG=1;;
    a)
	if ! [ "$OPTARG" -eq "$OPTARG" ] 2> /dev/null; then
		printf "\033[5;31mArgument for total recall mode is not an integer: %s\033[0m\n" "$OPTARG"
		exit 1;
	else
		AHEADDAYS="$OPTARG"
	fi
	;;
    r)
	RESCHEDULEFLAG=0;;
    z)
	ZENFLAG=1;;
    f)
	TAG="$OPTARG";;
    h|?)
	printf "Usage: %s: [-h] [-t] [-r] [-z] [-d deckfile] [-f tagregex] [-i cardfile] [-a days]
   -t\ttotal recall mode (due date ignored)
   -a\treview ahead by n days
   -r\tno rescheduling (deck is left unchanged)
   -z\tzen mode (screen clears between each review)
   -d\tselect deck file (default is db.tsv)
   -f\tfilter deck by tag (default is all tags)
   -i\timport mode (takes in tsv of front, back, and tags)
   -h\thelp\n" "$0"
	exit 2;;
    esac
done

if [ "$TOTALRECALLFLAG" = "1" ] && [ -n "$AHEADDAYS" ]; then
	printf "\033[5;31mCannot combine total recall mode and review ahead\033[0m\n"
	exit 2
fi

if [ -n "$IMPORTFLAG" ]; then
	import "$IMPORT"
else
	validate_deck "$DECK"
	if [ "$VALID" = "valid" ]; then
		printf '🐚 \033[1;35mmakigai \033[7;35mv0.0.1\n\033[0m\033[2;37mtype h for help\n\033[0m'
		create_temp_deck
		main
	else
		echo "$VALID"
		exit 2
	fi
fi
